[[headers]]
  for = "/_next/static/css/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/_next/static/chunks/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/_next/static/media/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"